name = "turbospotter"
main = "./src/server.js"
compatibility_date="2024-08-10"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

[vars]
ATLAS_APPID = "application-0-zdtzqku"

[[kv_namespaces]]
binding = "SPOTTED_COUNT"
id = "e36f74de240d4a329322bd13d452d291"